### PR TITLE
timer-support

### PR DESCRIPTION
**Pull request by bablokb**
This PR adds timer-support for the PCF8523 (timer-A, timer-B, watchdog-timer).

### CODE REVIEW

**Comment by bablokb** [comment]
Note: currently discussing with @tannewt memory impacts of my (besides hardware-specifics) identical pull-request for the PCF8563.

**Comment by dhalbert** [comment]
I have made this a draft because the corresponding PCF8563 PR,https://github.com/adafruit/Adafruit_CircuitPython_PCF8563/pull/6,  is still in progress, and the changes being made there. might analogously be made here.

**Comment by bablokb** [comment]
> I have made this a draft because the corresponding PCF8563 PR,[adafruit/Adafruit_CircuitPython_PCF8563#6](https://github.com/adafruit/Adafruit_CircuitPython_PCF8563/pull/6), is still in progress, and the changes being made there. might analogously be made here.

Yes, that was the plan. But nothing is happening there, I am waiting too.

**Comment by dhalbert** [comment]
OK, https://github.com/adafruit/Adafruit_CircuitPython_PCF8563/pull/6 is merged. Want to incorporate those changes too?

**Comment by bablokb** [comment]
I updated the code and also added examples for clock and timer.

**Pull request merged**
